import Head from "next/head";
import { AlternateGrid } from "../components/alternate-grid";
import { Contribution } from "../components/contribution";
import { VerticalStack } from "../components/vertical-stack";
import { Welcome } from "../components/welcome";

export default function Home() {
  return (
    <div>
      <Head>
        <title>CSS Flexbox Layouts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Welcome />
      <VerticalStack />
      <AlternateGrid />
      <Contribution />
    </div>
  );
}
